### ISSUE TITLE
Old version of Boost

### ISSUE THREAD

**Issue by fizwit** [wwylab/MuSE#10]
boost-1.70 is very old, and so is GCC 7.  Are there any plans to update the code to a more recent version of Boost?  I have built MuSE with 1.77.0.  Do you have any validation tests with data I could use to test with?

**Comment by jiyunmaths** [comment]
Hi @fizwit. Thanks for your comment. We are happy to test newer versions of boost and gcc for MuSE and hopefully release it in the near future.

**Comment by jiyunmaths** [comment]
We will include a newer version of Boost in a future version of MuSE.
