### ISSUE TITLE
segmentation fault errors - core dumped

### ISSUE THREAD

**Issue by pushpa-itagi** [wwylab/MuSE#13]
Hi,

I have been trying to run MUSE on few samples : WGS and always get errors of segmentation fault. It runs fine until a couple chromosomes and then throws the errors. 
P.S.: Both versions of Muse has had this error, but Muse-v2 is more faster. Can you please suggest a way to fix this? any suggestions on memory allocation or cores required?
It worked fine for most samples except two, so I am really looking for a fix to finish all runs.
Thank you for your time!

**Comment by jiyunmaths** [comment]
@pushpa-itagi Sorry for the error raised by MuSE. I am happy to fix it. Please visit the [Report an issue/bug section](https://github.com/wwylab/MuSE) and follow a template to report your issue, which could give us more information about it. Thanks.

**Comment by jiyunmaths** [comment]
Since the user did not follow up on this issue, I assume it is the same with #17.
