### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by balayev1** [wwylab/MuSE#15]
Hello,
Thank you for making the tool. I'm getting a Segmentation fault error upon running 'MuSE sump' command. I'm currently using MuSE version 2.0.3. The first step of the pipeline (i.e. MuSE call) has finished successfully with called mutations (link below) but second one fails with 'Segmentation fault'. Here is the command used:
`/home/aventeic/balay011/MuSE/MuSE sump -I /scratch.global/balay011/WGS_skChordomas_Bai/SomaticSNV_calling/work/muse/samples/462/462.MuSE.txt -O 462.MuSE.vcf -G -n 8
Segmentation fault`

I'm using following resources:
`srun -N 1 --cpus-per-task 8 --mem-per-cpu=16gb -t 5:00:00 -p interactive --pty bash`

Google drive link to gunzipped file: https://drive.google.com/file/d/1ZhDoFBLdWjFAuHNumpVqY3RBscaMSoYq/view?usp=drive_link

Thanks for your help.

Kind regards,
Agshin

**Comment by jiyunmaths** [comment]
Hi @balayev1, thank you for reporting this issue. I will fix it and update the repo soon.

**Comment by jiyunmaths** [comment]
Hi @balayev1 , I found why the error occurred. MuSE sump needs a snp database as one of the input. If you have not downloaded it, I refer you to download the `Homo_sapiens_assembly38.dbsnp138.vcf.gz` and its index file 'Homo_sapiens_assembly38.dbsnp138.vcf.gz.idx' from `https://console.cloud.google.com/storage/browser/genomics-public-data/resources/broad/hg38/v0`. Then you can run MuSE sump again use the command `home/aventeic/balay011/MuSE/MuSE sump -I /scratch.global/balay011/WGS_skChordomas_Bai/SomaticSNV_calling/work/muse/samples/462/462.MuSE.txt -O 462.MuSE.vcf -G -n 8 -D path_to_Homo_sapiens_assembly38.dbsnp138.vcf.gz`. Please let me know if you have more questions. Thanks.

**Comment by balayev1** [comment]
Thank you very much for your help!!!
