### ISSUE TITLE
Request: update conda package to latest version

### ISSUE THREAD

**Issue by famosab** [wwylab/MuSE#20]
I would like to integrate MuSE in a pipeline and everything would be easier if it was available as conda package. I saw that the [Version 1.0 was published to bioconda](https://anaconda.org/bioconda/muse). Maybe you can also do it with Version 2!

**Comment by famosab** [comment]
FYI: I will try and update the Package recipe: https://bioconda.github.io/recipes/muse/README.html If it works I'll close the issue :)

**Comment by famosab** [comment]
See https://github.com/bioconda/bioconda-recipes/pull/47957

**Comment by jiyunmaths** [comment]
@famosab Thank you for working on the conda package of MuSE 2. Please note MuSE 2 relies on more C/C++ libraries than MuSE 1 and it also has a more complicated building process than the old version.

**Comment by famosab** [comment]
I just mentioned you in the PR. I am unsure how to continue and integrate the dependencies in the build.sh

**Comment by mencian** [comment]
`MuSE` conda package has been updated to `v2.1.2` [here](https://github.com/bioconda/bioconda-recipes/pull/47957). I've disabled the build on `osx` as per the documentation.

**Comment by Coaxecva** [comment]
@mencian Thank you for taking care of this.
@famosab I'm going to close the issue. Feel free to re-open if you have any other questions.
