### ISSUE TITLE
Empty VCF file after sump

### ISSUE THREAD

**Issue by IsMM15** [wwylab/MuSE#25]
Hello! I am trying to run MuSE on an exome sample with the following command `MuSE sump -I test.MuSE.txt -O test.MuSE.vcf  -G -D Homo_sapiens_assembly38.dbsnp138.vcf.gz`  

The first part (MuSE call) runs fine without issues and outputs a txt file of 120megabytes, but after running the sump command the output is a VCF file that has only the header. 
Any guesses on what might be happening and how to fix it? 

Thanks!

**Comment by jiyunmaths** [comment]
Hi @IsMM15 , I guess you missed the option `-n x` when ran `MuSE sump`. `x` is the number of cores for running this step.  Please can you try 
`MuSE sump -I test.MuSE.txt -O test.MuSE.vcf  -G -n 10 -D Homo_sapiens_assembly38.dbsnp138.vcf.gz`? Let me know if you still have the issue.

**Comment by jiyunmaths** [comment]
This issue is closed.
