### ISSUE TITLE
question about sump -D option

### ISSUE THREAD

**Issue by balabanmetin** [wwylab/MuSE#26]
Hello, 
I run Muse sump with -D option and provide a dbSNP VCF file. What exactly does -D do? 

If there are somatic variants at dbSNP positions (in other words; germline match normal is homozygous REF allele and tumor is heterozygous), will this position be present in the output of Muse sump?

 In my tests, this seems to be the case. Is this by design? Or the developers intended to strictly filter out the dbSNP positions in the output but there might be a bug?

**Comment by jiyunmaths** [comment]
Hi @balabanmetin , The `-D dbSNP` option searches for each candidate variant (called by MuSE) in the dbSNP database and labels those found in the database. The final variants in the VCF file may include mutations at dbSNP positions, but these mutations are subjected to a more stringent cutoff compared to those found at non-dbSNP positions. You can find more information in our paper: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1029-6.
