### ISSUE TITLE
Hard coded version

### ISSUE THREAD

**Issue by sorelfitzgibbon** [wwylab/MuSE#27]
Thanks again for the terrific software!
Minor issue: If I understand correctly, it appears the version number is fixed at v2.0, even with the latest v2.1.1:
https://github.com/wwylab/MuSE/blob/2eb286ffb427f0f258d16b1a5e8b0b3f410bc7f6/src/muse_call.cpp#L9

**Comment by jiyunmaths** [comment]
Hi @sorelfitzgibbon Sorry for the confusion. This is a mistake. We just updated 'v2.0' to the latest 'v2.1.1' in this line.

**Comment by sorelfitzgibbon** [comment]
Thanks @jiyunmaths !   Any chance of a new release for this?  I'm building from a dockerfile that I'd like to release.

**Comment by jiyunmaths** [comment]
@sorelfitzgibbon Sure. I released the new version which fixed the error. Please use V2.1.2. Thank you.

**Comment by jiyunmaths** [comment]
The question was addressed.
