### ISSUE TITLE
Usage of indexed files

### ISSUE THREAD

**Issue by famosab** [wwylab/MuSE#31]
While working on the nf-core modules I encountered two things which I could not determine from the docs:

1. Does the tool use the indexes of the sorted bam files if they are present? And does MuSE expect the index to be passed alongside the bam file?
2. What exactly is meant by "faidx indexed reference genome file"? When I tested the tool it seemed to me that just the genome fasta file was sufficient.

**Comment by jiyunmaths** [comment]
Hi @famosab, Yes, both MuSE 1 and MuSE 2 utilize the index files of BAM files to efficiently access reads at specific genomic locations. If these index files are missing, please generate them using tools such as Samtools or GATK before running MuSE.
For the reference genome index file, MuSE 1 required it to quickly retrieve the reference allele at a specified genomic position. In contrast, MuSE 2 leverages an in-memory dictionary data structure that stores the entire reference genome, enabling it to access the reference allele directly without needing an index file. As a result, the reference genome index file is no longer required for MuSE 2.

**Comment by famosab** [comment]
Thanks for the detailed answer :) 
Maybe you can extend the docs to add the info of the indices!
