### ISSUE TITLE
MuSE docker dependency packages

### ISSUE THREAD

**Issue by maotian06** [wwylab/MuSE#4]
This is not a bug, but when I tried to use the provided 'Dockerfile' to build the docker image in our GitHub container registry, we found a few dependencies related to MuSE V2.0.

Because our linter checks for `Dockerfile` need to use `--no-install-recommends` option for `apt-get update && apt-get install`. So we added other dependency packages, here is the command we used in that section:
```
RUN apt-get update && apt-get install -y --no-install-recommends \
    git g++ cmake autoconf libtool liblzma-dev zlib1g-dev libbz2-dev libcurl3-dev libssl-dev \
    ca-certificates cpp make libltdl-dev wget unzip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
```
This might help reduce the docker image size~ Hope it helps!!!

**Comment by jiyunmaths** [comment]
@maotian06 Thanks Mao. It's a good idea. Thanks for your suggestion. I am happy to include it in our next update.
