### ISSUE TITLE
`bgzip` issue during `MuSE sump`

### ISSUE THREAD

**Issue by maotian06** [wwylab/MuSE#5]
@jiyunmaths 
This error occurred during the `MuSE sump` process when processing both WGS and WXS samples. However, this is unstable and cannot be reproduced regularly during multiple test runs.
The error message is:

```
  Was bgzip used to compress hg38_All_20180418.vcf.gz?
```

**Comment by jiyunmaths** [comment]
@maotian06 . Thanks for your comment. Sorry I have not met this issue.  I'd like to suggest doing the following steps for the dbsnp 
```
gzip -d hg38_All_20180418.vcf.gz
bgzip -c hg38_All_20180418.vcf > hg38_All_20180418.vcf.gz
tabix -p hg38_All_20180418.vcf.gz
```

**Comment by maotian06** [comment]
Thanks for the suggestion! @jiyunmaths 
This is not a stable error, and once I switched to the latest dbSNP, this didn't happen. I will let you know if this error occurs again.
