### ISSUE TITLE
Minimal output from MuSE call

### ISSUE THREAD

**Issue by deniando** [wwylab/MuSE#6]
Hi,

I do not think I am getting the expected output from MuSE call (see attached). It runs without errors but the output contains minimal information. How important is it that we perform the exact pre-processing steps you have outlined? We have our own pre-processing pipeline and have not used all the same software for each step of the pre-processing pipeline that you have outlined. I assumed MuSE would still work with our processed BAMs but maybe that is not the case?

Thanks,

Denise

[12-01_S3_L001.MuSE.txt](https://github.com/wwylab/MuSE/files/9856772/12-01_S3_L001.MuSE.txt)

**Comment by jiyunmaths** [comment]
@deniando Sorry for addressing your issue late. I think the reason for the empty MuSE.txt file is that you use a compressed reference genome file "GRCh38.primary_assembly.genome.fa.gz". Please can you uncompress it (gzip -d GRCh38.primary_assembly.genome.fa.gz) and run MuSE call again? Let me know if you still have the problem. 
The preprocessing steps are important, please follow the tutorial. Thanks.

**Comment by deniando** [comment]
That was the issue @jiyunmaths, thanks very much for your help.
