### ISSUE TITLE
Variance going to zero error during `MuSE sump`

### ISSUE THREAD

**Issue by jdc8890** [wwylab/MuSE#7]
Hi,

I'm running MuSE on some WGS data but am running into an error when calling `sump`.  The `call` command works fine and seems to generate the appropriate output (~1 GB file per sample), but when I run `sump`, the process hangs for a while before finally outputing the following and then terminating:

```
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
One of the variances is going to zero; trying new starting values.
Too many tries!
```

Any guidance to help troubleshoot would be much appreciated.  Many thanks in advance.

**Comment by jiyunmaths** [comment]
@jdc8890 Thanks for using MuSE. Sorry for the trouble. I have not seen this error before. Please can you share the output from MuSE call step with us? I will debug the code and fix the error. You can zip it to reduce the size. Thanks.

**Comment by jdc8890** [comment]
@jiyunmaths Thank you for your help.  I was able to successfully run sump on this output with MuSE 1.0, so the error seems to be related to version 2.0+.  The output from MuSE call to too big to attach here (i.e. >25 MB)--is there another way I can send it to you to help with debugging?

**Comment by jiyunmaths** [comment]
@jdc8890 Please can you share it with me via google drive? My email is jiyunmathbhamATgmail.com. Thank you very much!

**Comment by jiyunmaths** [comment]
Hi @jdc8890. Apologize for the late reply. I have fixed the issue which is related to multiple read groups in the BAM files. I also did many benchmarking to confirm the solution. You can download the source code and compile again. Thank you for using MuSE!

**Comment by wwylab** [comment]
I believe this issue has been addressed.
