### ISSUE TITLE
MuSE is using too many threads

### ISSUE THREAD

**Issue by skchronicles** [wwylab/MuSE#8]
Hello there,

I just wanted to start off by saying thank you for creating and maintaining MuSE. It is an awesome somatic caller! 

Recently while running MuSE/2.0.1 (exact commit 105c5be01c43dbe8cc29803e2ab87f35f6f3589a), I noticed that it is using more threads than I have told it to use:
![image](https://github.com/wwylab/MuSE/assets/18038345/6d5c79ef-bb65-4b88-a9a8-b1a49ee4092d)
 
For the job above, I ran MuSE with `-n 32`; however, it is using 41/42 threads. I am running MuSE on a cluster with other users, so its over-allocation impacts other people's jobs. 

Here is a log file containing the commands that were run:
```sh
$ MuSE call \
        -n 32 \
        -f GRCh38p11.fasta \
        -O muse/somatic/WGS_NCI_T_S1 \
       BAM/WGS_NCI_T_S1.recal.bam BAM/WGS_NCI_N_S2.recal.bam 

$ MuSE sump \
        -n 32 \
        -G \
        -I muse/somatic/WGS_NCI_T_S1.MuSE.txt \
        -O muse/somatic/WGS_NCI_T_S1.muse.tmp.vcf \
        -D GATK_resource_bundle/hg38bundle/dbsnp_146.hg38.vcf.gz
```

If you could please take some time to look into this issue, that would be amazing! Thank you again for your time, and have a wonderful day.

Best Regards,
@skchronicles

**Comment by jiyunmaths** [comment]
Hi @skchronicles, thanks for using MuSE! Sorry for the confusing. There are actually 9 more threads used than the number specified in the command (e.g., MuSE call -n 32) when run MuSE. The 9 threads are used for parsing BAM chunks, unzipping BAM chunks, merging reads from tumor and normal into the same queue and writing candidate SNVs into file etc. 
The 32 threads specified by the user are for reads processing and inferring candidate SNVs, which take the majority of CPU resources. From my experience, even though 41/42 threads are used, the CPU resource usage does not exceed 3200% (32 CPU cores) too much. Please go ahead and test it and let me know if much more CPU core resources are used. I will update the README and clear this confusion.

**Comment by skchronicles** [comment]
Hey @jiyunmaths,

Thank you for your prompt and detailed response! 

Would it be possible to add some logic to prevent this from occurring in a future release (no rush)? This would prevent the user from needing to do anything on their side. Instead of allocating N threads for (e.g. 32) processing/inferring candidate SNVs, you could spawn N-9 threads (e.g. 32-9). 

If not, that's totally okay. I will run MuSE with `-n N-9` moving forward.

Thank you again for your time and help. I appreciate it!

Best Regards,
@skchronicles

**Comment by jiyunmaths** [comment]
@skchronicles Thanks for suggestion! I will consider to update the flag in the future release.

**Comment by skchronicles** [comment]
Okay, that sounds good. 

Have a great weekend,
@skchronicles

**Comment by Coaxecva** [comment]
I see your point, @0xaf1f . I've created a branch that addresses this by setting the default `-n 10`, which ensures at least one worker thread is available. If a user provides a value less than 10, the program now exits with a clear error:

> [ERROR] Minimum total thread count is 10. You requested 9. Exiting without execution.

If -n is 10 or greater, it automatically reserves 9 threads for core modules and uses the remainder for parallel processing. For example,`-n 11`:

> [INFO] Using 9 reserved threads for core modules. 2 threads will be used for parallel processing.

You can check out the branch here:
https://github.com/wwylab/MuSE/tree/thread-handling-update

The help message (MuSE call) has also been updated to reflect this:

> -n INT     number of total threads (default = 10; minimum = 10)

Thanks again for helping clarify the expectations!

**Comment by 0xaf1f** [comment]
Wow, thank you! That looks perfect.
