### ISSUE TITLE
MuSE v2 Region Parameter

### ISSUE THREAD

**Issue by fahadkh** [wwylab/MuSE#9]
Hi!

MuSE v1 featured a region flag for calling variants only on specific regions. Are there plans to add this parameter to MuSE v2 or is the intention that the improved runtime means we should just allow MuSE to call variants everywhere and filter downstream?

**Comment by jiyunmaths** [comment]
Hi @fahadkh, we removed the option in MuSE 2.0 since this step will complicate the coding, as well as MuSE 2.0 is much faster than MuSE 1.0.  If your genomic region of interest is not large, I think MuSE 1.0 is a better choice. Thanks.

**Comment by fahadkh** [comment]
Ok, thank you.
